### ISSUE TITLE
Route.gzb 

### ISSUE THREAD

**Issue by nibornosskire** [rsc-dev/loophole#12]
Hi! How should i process the data from Route.gzb to make sense? Using protoc raw to decode but the GPS cordinates doesnt make sense for me! Thanks!

**Comment by rsc-dev** [comment]
Hi. Route.gzb is zipped file. Please unzip it and try to decode.

**Comment by nibornosskire** [comment]
Yes i know! But when unzipped and decoded with protoc decode_raw the data looks like:
9 {
  1 {
    1: 2017
    2: 4
    3: 22
  }
  2 {
    1: 14
    2: 8
    3: 45
    4: 0
  }
  3: 1
}
5: "\n"
2: "\017\222\030\027!\353M@"
3: "\306\003\267\333\033I&@"
4: "\204\003"
1: "\350\273B"

where the gps-values does'nt make sense to me.. What format are they in and, how should i parse/decode them to get standard lat/long?

**Comment by rsc-dev** [comment]
Could you please attach Route.gzb file?

**Comment by nibornosskire** [comment]
Here you go, its unziped, just renamed it to zip to have it uploaded..

[ROUTE.zip](https://github.com/rsc-dev/loophole/files/1009933/ROUTE.zip)

**Comment by rsc-dev** [comment]
Thank you. I will check it.

**Comment by rsc-dev** [comment]
Hi. Route file parsing is not implemetned. You can write own simple script to read this file:

from polar.pb import exercise_route_pb2 as route_pb

with open('ROUTE', 'rb') as fh:
    v = route_pb.PbExerciseRouteSamples.FromString(fh.read())
    print v

**Comment by nibornosskire** [comment]
Thanks! Just trying to figure out how to convert a value like 2: "\017\222\030\027!\353M@" into latitude manually, but i guess i could find out looking into exercise_route.proto/.py and types.proto/.py

**Comment by rsc-dev** [comment]
Ok.
All files in pb directory are autogenerated from Polar protocol buffers descriptors. 
Reversing string you mentioned is like reversing PB (https://developers.google.com/protocol-buffers/docs/overview).

Plain PB descriptor for ROUTE can be found in protocol_buffers/data/exercise_route.proto.

**Comment by nibornosskire** [comment]
Thanks, i see! Also have a question regarding your scrip pbd, but i will put it in that repository!

**Comment by rsc-dev** [comment]
Please use gitter if it is not an issue: https://gitter.im/rsc-dev/pbd.

Best regards
Radek
