### ISSUE TITLE
convert  polar byte array into txt files

### ISSUE THREAD

**Issue by smkresearch** [rsc-dev/loophole#7]
We want to use a  polar A360 in our hospital.  And as you can imaging we are not happy  (and allowed to) to send de data of our patients into the Polar cloud. So I was very happy to find your software. 
I installed the software onto a windows system en was able to connect en read/dump the files from the connected device.  I nerver used python before  so as far I can understand  you use the protocol buffers to decode the files when they are read from the device but how can I convert the files into a readable format ( e.g text )  so we can use then in excel ?
Regards
Bart Nienhuis

**Comment by rsc-dev** [comment]
Hi,

This sounds great. You are right - I am using protocol buffers to decode data.
I am not sure, which data you are interested the most. 
All protocol buffers can be find https://github.com/rsc-dev/loophole/tree/master/protocol_buffers/data.

Please sign in to gitter (https://gitter.im/rsc-dev/loophole) and send me PM. 
I am more than happy to help in this project.

Best regards
Radek

**Comment by fernsehkind** [comment]
I just had the same problem and I didn't want to upload my personal data
to the cloud.

I use a raspberry pi with a tiny webserver to access my activity data
just using a browser on any device in my local network. I also use
loophole to fetch the data from the device. If you want to have a look
at an example how to use loophole, visit
https://github.com/fernsehkind/PALOR/tree/master/backend.

If you want to use excel you may have a look at
https://github.com/mgravell/protobuf-net. With the definitions from
https://github.com/rsc-dev/loophole/tree/master/protocol_buffers/data
you can easily convert it to an excel file using any language supporting
.NET.

Regards


Am 14.12.2016 um 12:31 schrieb smkresearch:

**Comment by rsc-dev** [comment]
This was resolved with project A360: https://github.com/rsc-dev/A360
